config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get '/chatroom', to: 'chats#index', as: 'chat'
    post 'chats', to: 'chats#create'
    get 'contact_us', to: 'messages#contact_us', as: 'contact_us'
    post 'contact_us', to: 'messages#create'
    resources :news do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callbacks, controllers:
      {
        registrations: 'devise_overrides/registrations'
      }
    resources :users
    resources :projects do
      resources :project_participants, as: 'participants'
    end
    root to: 'news#index'
    resources :categories
    resources :users do
      get :update_password
      patch :update_password
      get :edit_password
    end
    get '/users/:id/news', to: 'news#user_news', as: :user_news
    get '/users/:id/events', to: 'events#user_events', as: :user_events
    get :approve, to: 'email_change_requests#approve'
    resources :email_change_requests
    resources :events do
      member do
        post :subscribe
        post :unsubscribe
      end
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers:
    {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
end

app/views/shared/_footer.html.haml
%nav.navbar.navbar-expand-sm.bg-light.footer
  %ul.navbar-nav
    %li.nav-item
      %a.nav-link{ href: '#' }
        = t('shared.header.news')
    %li.nav-item
      %a.nav-link{ href: events_path }
        = t('shared.header.events')
    %li.nav-item
      %a.nav-link{ href: '#' }
        = t('shared.header.for_entrants')
    %li.nav-item
      %a.nav-link{ href: '#' }
        = t('shared.header.about_us')
    %li.nav-item
      = link_to t('shared.header.contacts'), contact_us_path, class: 'nav-link'
  %ul.navbar-nav.ml-auto
    %li.nav-item
      %a
        = link_to 'EN', url_for(locale: :en)
        |
        = link_to 'UK', url_for(locale: :uk)

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-sm.bg-light.justify-content-between
  %ul.navbar-nav
    %li.nav-item
      %a.nav-link{ href: news_index_path }
        = t('shared.header.news')
    %li.nav-item
      %a.nav-link{ href: events_path }
        = t('shared.header.events')
    %li.nav-item
      %a.nav-link{ href: '#' }
        = t('shared.header.for_entrants')
    %li.nav-item
      %a.nav-link{ href: '#' }
        = t('shared.header.about_us')
    %li.nav-item
      = link_to t('shared.header.contacts'), contact_us_path, class: 'nav-link'
    %li.nav-item
      = link_to t('shared.header.create_news'), new_news_path, class: 'nav-link'
    %li.nav-item
      = link_to t('shared.header.users'), users_path, class: 'nav-link'
  %ul.navbar-nav
    %li.nav-item
      - if user_signed_in?
        = t('shared.header.logged_in')
        = succeed '.' do
          %strong
            = link_to current_user.email, user_path(current_user.id, locale: I18n.locale)

        = link_to t('shared.header.edit_profile'),
            edit_user_path(current_user.id, locale: I18n.locale),
            class: 'navbar-link'
        |
        = link_to t('shared.header.logout'),
            destroy_user_session_path,
            method: :delete, class: 'navbar-link'

      - else
        = link_to t('shared.header.sign_up'),
            new_user_registration_path,
            class: 'navbar-link'
        |
        = link_to t('shared.header.login'),
            new_user_session_path,
            class: 'navbar-link'

app/views/shared/_notifications.html.haml
- if notice.present?
  .notice.alert.alert-info
    = notice
- if alert.present?
  .alert.alert-danger
    = alert