config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get '/chatroom', to: 'chats#index', as: 'chat'
    post 'chats', to: 'chats#create'
    get 'contact_us', to: 'messages#contact_us', as: 'contact_us'
    post 'contact_us', to: 'messages#create'
    resources :news do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callbacks, controllers:
      {
        registrations: 'devise_overrides/registrations'
      }
    resources :users
    resources :projects do
      resources :project_participants, as: 'participants'
    end
    root to: 'news#index'
    resources :categories
    resources :users do
      get :update_password
      patch :update_password
      get :edit_password
    end
    get '/users/:id/news', to: 'news#user_news', as: :user_news
    get '/users/:id/events', to: 'events#user_events', as: :user_events
    get :approve, to: 'email_change_requests#approve'
    resources :email_change_requests
    resources :events do
      member do
        post :subscribe
        post :unsubscribe
      end
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers:
    {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  include AASM
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200 }
  validates :description, :venue, :event_start, :event_end, presence: true
  validates :cost, numericality: { greater_than_or_equal_to: 0 }

  validate :event_end_after_event_start, :event_start_is_past_date,
           :event_end_is_past_date

  scope :upcoming_events, -> { where('event_start >= ?', Time.now).order(:event_start) }
  scope :next_events, ->(event) { upcoming_events.where.not(id: event.id).limit(3) }

  aasm column: 'state' do
    state :draft, initial: true
    state :rejected
    state :sheduled
    state :past
    state :archived

    event :reject do
      transitions from: [:draft], to: :rejected
    end
    event :shedule do
      transitions from: [:draft], to: :sheduled
    end
    event :past do
      transitions from: [:sheduled], to: :past
    end
    event :archive do
      transitions from: %i[sheduled past draft], to: :archived
    end
  end

  private

  def event_end_after_event_start
    return if event_end.blank? || event_start.blank?

    errors.add(:event_end, I18n.t('events.errors.after')) if event_end < event_start
  end

  def event_start_is_past_date
    return if event_start.blank?

    errors.add(:event_start, I18n.t('events.errors.future')) if event_start < Time.now
  end

  def event_end_is_past_date
    return if event_end.blank?

    errors.add(:event_end, I18n.t('events.errors.future')) if event_end < Time.now
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update destroy]
  before_action :authenticate_user!, except: %i[show index user_events]
  before_action :set_event_subscribe, only: %i[subscribe unsubscribe]

  def index
    @events = Event.upcoming_events
  end

  def show
    @event = Event.find(params[:id])
    @next_events = Event.next_events(@event)
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to events_path, notice: t('.notice')
    else
      render 'new', alert: t('.alert')
    end
  end

  def subscribe
    @event.participants << current_user
    redirect_to event_path(@event), notice: t('.notice_yes')
  end

  def unsubscribe
    @event.participants.delete(current_user.id)
    redirect_to event_path(@event), notice: t('.notice_no')
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: t('.notice')
    else
      render 'edit', alert: t('.alert')
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path, notice: t('.notice')
    else
      redirect_to events_path, alert: t('.alert')
    end
  end

  def user_events
    @user = User.find(params[:id])
    @events = Event.where(user_id: params[:id]).paginate(page: params[:page], per_page: 6)
  end

  private

  def set_event
    @event = current_user.created_events.find(params[:id])
  end

  def set_event_subscribe
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :venue, :event_start,
                                  :event_end, :cost)
  end
end

app/views/events/_event.html.haml
.col-md-4.mb-4
  .event-img.mb-2
    %img{ src: 'https://mdbootstrap.com/img/Photos/Others/img%20(27).jpg' }
  %h4.m-0.d-inline
    %strong
      = event.title
  %p.mt-2.mb-2
    %em
      = event.event_start.strftime('%d %b %Y')
  %p.text-dark.mb-1
    = truncate(strip_tags(event.description.html_safe), length: 200)
  %h6.m-0.text-dark
    = link_to t('news.links.read_more'), event_path(event)

app/views/events/_form.html.haml
= form_for @event do |form|
  %p
    = t('events.form.title')
  %p
    = form.text_field :title, { class: 'form-control' }
  %ol
    - @event.errors[:title].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('events.index.start')
  %p
    = form.datetime_local_field :event_start, { min: Date.today, class: 'form-control' }
    %small
      mm/dd/yyyy hh:mm m
  %ol
    - @event.errors[:event_start].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('events.index.end')
  %p
    = form.datetime_local_field :event_end, { min: Date.today, class: 'form-control' }
    %small
      mm/dd/yyyy hh:mm m
  %ol
    - @event.errors[:event_end].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('events.index.venue')
  %p
    = form.text_field :venue, { class: 'form-control' }
  %ol
    - @event.errors[:venue].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('events.form.cost')
  %p
    = form.text_field :cost, { class: 'form-control' }
  %ol
    - @event.errors[:cost].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('events.form.description')
  %p.text-left.h5
    = form.text_area :description, { class: 'form-input tinymce', rows: 12 }
  %ol
    - @event.errors[:description].each do |msg|
      %li.text-danger
        = msg
  %p
    %strong
      = t('events.form.organizer_msg')
  %p.text-right
    = form.submit t('events.form.submit'), class: 'btn btn-outline-dark'
  %ol.text-left

app/views/events/_next_events.html.haml
.col-md-3
  .card-header
    %h3.mb-0
      = t('events.show.next_events')
  .card-body
    %ul.list-unstyled
      - @next_events.each do |event|
        %li.media
          .media-body
            %h4.mt-0.mb-1.font-weight-bold
              %strong
                %a.text-black{ href: event_path(event) }
                  = event.title.html_safe
            %p
              %em
                = event.event_start.strftime('%d %b %Y')
            %p.mb-1
              = truncate(strip_tags(event.description.html_safe), length: 100)
        %hr

app/views/events/edit.html.haml
.container
  %section.mt-4
    .row.justify-content-center
      .col-md-8.mb-4
        %h3.text-center.mb-4
          = t('events.edit.edit_event')
        = render 'form'

app/views/events/index.html.haml
.container
  .row.justify-content-center.mt-4
    .col-lg-9
      %h3.mb-4
        = t ('events.index.upcoming_events')
      .m-0.text-right.d-inline
        %p
          = link_to t('events.index.create'), new_event_path
      .row.mb-4
        = render @events

app/views/events/new.html.haml
.container
  %section.mt-4
    .row.justify-content-center
      .col-md-8.mb-4
        %h3.text-center.mb-4
          = t('events.new.add_event')
        = render 'form'

app/views/events/show.html.haml
.container
  %section.mt-4
    .row.justify-content-center
      .col-md-8
        .card-body
          %h1.display-2.m-0.mb-4.mr-2
            = @event.title
          .m-0.text-right.d-inline
            %p
              - if current_user && current_user == @event.user
                = link_to t('news.links.edit'), edit_event_path(@event)
                |
                = link_to t('news.links.delete'), event_path(@event), { method: :delete }
          .row
            .col-md-4
              %h4.text-left.mt-2
                %strong
                  = t ('events.index.organizer')
            .col-md-6
              %h4.text-left.mt-2
                = @event.user.first_name.html_safe
                = @event.user.last_name.html_safe
          - if @event.event_start.to_date == @event.event_end.to_date
            .row
              .col-md-4
                %h4.text-left.mt-2
                  %strong
                    = t ('events.index.date')
              .col-md-6
                %h4.text-left.mt-2
                  = @event.event_start.strftime('%d %b %Y')
            .row
              .col-md-4
                %h4.text-left.mt-2
                  %strong
                    = t ('events.index.time')
              .col-md-6
                %h4.text-left.mt-2
                  = @event.event_start.strftime('%H:%M')
                  = t ('events.index.sign')
                  = @event.event_end.strftime('%H:%M')
          - else
            .row
              .col-md-4
                %h4.text-left.mt-2
                  %strong
                    = t ('events.index.start')
              .col-md-6
                %h4.text-left.mt-2
                  = @event.event_start.strftime('%d %b %Y %H:%M')
            .row
              .col-md-4
                %h4.text-left.mt-2
                  %strong
                    = t ('events.index.end')
              .col-md-6
                %h4.text-left.mt-2
                  = @event.event_end.strftime('%d %b %Y %H:%M')
          .row
            .col-md-4
              %h4.text-left.mt-2
                %strong
                  = t ('events.index.venue')
            .col-md-6
              %h4.text-left.mt-2
                = @event.venue.html_safe
          .row
            .col-md-4
              %h4.text-left.mt-2
                %strong
                  = t ('events.index.cost')
            .col-md-6
              %h4.text-left.mt-2
                - if @event.cost.zero?
                  = t ('events.index.free')
                - else
                  = @event.cost
                  = t ('events.show.currency')
          %h4.text-left.mt-4.mb-4
            = @event.description.html_safe
          %h4.text-left.mt-2.mb-2
            %strong
              = t ('events.show.attendees')
            = @event.participants.count
          %h4.text-left.mt-2.mb-2
            - unless current_user && current_user == @event.user
              = t ('events.show.question')
              - if @event.participants.find_by(id: current_user.id)
                = link_to t('events.show.ans_no'), unsubscribe_event_path(@event), method: :post,
                  class: 'btn btn-outline-dark mt-0'
              - else
                = link_to t('events.show.ans_yes'), subscribe_event_path(@event), method: :post,
              class: 'btn btn-outline-dark mt-0'
          %br
      = render 'next_events'

app/views/events/user_events.html.haml
.container.p-0
  %h1.mb-3
    = t ('users.edit.profile')
  .row
    .col-md-5.col-xl-3
      = render 'users/menu', user: @user
    .col-md-7.col-xl-9
      .card
        .card-header
          %h5.card-title.mb-0
            = t ('users.edit.events')
        .card-body
          .row.mb-6
            = render @events.upcoming_events
          = will_paginate @events