config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get '/chatroom', to: 'chats#index', as: 'chat'
    post 'chats', to: 'chats#create'
    get 'contact_us', to: 'messages#contact_us', as: 'contact_us'
    post 'contact_us', to: 'messages#create'
    resources :news do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callbacks, controllers:
      {
        registrations: 'devise_overrides/registrations'
      }
    resources :users
    resources :projects do
      resources :project_participants, as: 'participants'
    end
    root to: 'news#index'
    resources :categories
    resources :users do
      get :update_password
      patch :update_password
      get :edit_password
    end
    get '/users/:id/news', to: 'news#user_news', as: :user_news
    get '/users/:id/events', to: 'events#user_events', as: :user_events
    get :approve, to: 'email_change_requests#approve'
    resources :email_change_requests
    resources :events do
      member do
        post :subscribe
        post :unsubscribe
      end
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers:
    {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
end

app/models/news.rb
# frozen_string_literal: true

class News < ApplicationRecord
  include AASM
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, as: :commentable
  belongs_to :category

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true
  validates :short_information, presence: true, length: { maximum: 200 }

  scope :ordered_by_views, -> { order(views: :desc) }
  scope :by_categories, ->(category) { where(category: category) }
  scope :ordered, -> { order(created_at: :desc) }
  scope :search, ->(search) { where('title ILIKE lower(?)', "%#{search}%") }

  aasm column: 'state' do
    state :draft, initial: true
    state :rejected
    state :published
    state :archived

    event :reject do
      transitions from: [:draft], to: :rejected
    end
    event :publish do
      transitions from: [:draft], to: :published
    end
    event :unpublish do
      transitions from: [:published], to: :draft
    end
    event :archive do
      transitions from: %i[published draft], to: :archived
    end
  end
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  before_action :find_current_user_news, only: %i[edit update destroy]

  has_scope :ordered_by_views, type: :boolean, only: %i[index]
  has_scope :by_categories, type: :array, only: %i[index]
  before_action :authenticate_user!, except: %i[index show user_news]

  def index
    @categories = Category.all
    search = params[:title_search]
    @news = apply_scopes(News).ordered.search(search).paginate(page: params[:page], per_page: 3)
    flash.now[:alert] = t('.alert') if @news.empty?
    respond_to :js, :html
  end

  def show
    @news = News.find(params[:id])
    @news.increment!(:views)
    @commentable = @news
    @comments = @news.comments.order(:created_at)
    @comment = Comment.new
  end

  def new
    @news = News.new
  end

  def edit; end

  def create
    @news = current_user.news.build(news_params)
    if @news.save
      redirect_to news_index_path, notice: t('.notice')
    else
      render 'new', alert: t('.alert')
    end
  end

  def update
    if @news.update(news_params)
      redirect_to @news, notice: t('.notice')
    else
      render 'edit', alert: t('.alert')
    end
  end

  def destroy
    if @news.destroy
      redirect_to news_index_path, notice: t('.notice')
    else
      redirect_to news_index_path, alert: t('.alert')
    end
  end

  def user_news
    @user = User.find(params[:id])
    @news = News.where(user_id: params[:id]).paginate(page: params[:page], per_page: 5)
  end

  private

  def news_params
    params.require(:news).permit(:title, :short_information, :body, :image, :category_id)
  end

  def find_current_user_news
    @news = current_user.news.find(params[:id])
  end
end

app/views/news/_aside_bar.html.haml
.col-lg-4
  %h3.font-weight-bold
    = t('news.aside_bar.about_university')
  %hr
  .row.justify-content-end
    .col-lg-11
      %h5.m-0.ml-10
        = link_to t('news.aside_bar.leadership_and_organisation'), '#', class: 'text-dark'
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      %h5.m-0
        = link_to t('news.aside_bar.education'), '#', class: 'text-dark'
      %p
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
        ut aliquip ex ea commodo consequat.
      %h5.m-0
        = link_to t('news.aside_bar.students_community'), '#', class: 'text-dark'
      %p
        Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat.
        %h3.font-weight-bold
  %h3.font-weight-bold
    = t('news.aside_bar.life_at_university')
  %hr
  .row.justify-content-end
    .col-lg-11
      %h5.m-0.ml-10
        = link_to t('news.aside_bar.arts_and_culture'), '#', class: 'text-dark'
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      %h5.m-0
        = link_to t('news.aside_bar.sports'), '#', class: 'text-dark'
      %p
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
        ut aliquip ex ea commodo consequat.
  %hr

app/views/news/_form.html.haml
= form_for @news do |form|
  %p
    = t('news.form.title')
  %p
    = form.text_field :title, { class: 'form-control' }
  %ol
    - @news.errors[:title].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('news.form.short_information')
  %p
    = form.text_field :short_information, { class: 'form-control' }
  %ol
    - @news.errors[:short_information].each do |msg|
      %li.text-danger
        = msg
  %p
    = form.collection_select(:category_id, Category.all, :id, :name,
    {prompt: 'Select news category'})
  %ol
    - @news.errors[:category_id].each do |msg|
      %li.text-danger
        = msg
  %p
    = t('news.form.body')
  %p.text-left.h5
    = form.text_area :body, { class: 'form-input tinymce', rows: 12 }
  %p
    = t('news.form.image')
  %p.text-left.h5
    = form.file_field :image, { class: 'form-input' }
  %ol
    - @news.errors[:body].each do |msg|
      %li.text-danger
        = msg
  %p.text-right
    = form.submit t('news.form.submit'), class: 'btn btn-outline-dark'
  %ol.text-left

app/views/news/_news.html.haml
- @news.each do |news|
  %hr
  .row
    .col-lg-8
      %h4.m-0.d-inline
        = news.title
      %p.m-0.text-right.d-inline
        - if current_user && current_user == news.user
          = link_to t('news.links.edit'), edit_news_path(news)
          |
          = link_to t('news.links.delete'), news_path(news), { method: :delete }
      %p.text-dark
        = news.short_information
      %p.mb-1
        = t ('news.links.written_by')
        %strong
          = link_to_user(news.user)
          %br
          = t('news.links.created_at')
          = news.created_at.to_date
      %h5.m-0.text-dark
        = link_to t('news.links.read_more'), news_path(news)
        = fa_icon 'eye', text: news.views, class: 'ml-4'
        = fa_icon 'tags', text: t('news.links.category'), class: 'ml-4'
        = link_to news.category.name
    .col-lg-4
      .thumbnail
        = image_tag news.image_url(:thumb)

app/views/news/_related_news.html.haml
.col-md-3
  .card-header
    = t('news.show.related_news')
  .card-body
    %ul.list-unstyled
      %li.media
        .media-body
          %a.text-black{ href: '' }
            %h5.mt-0.mb-1.font-weight-bold
              List-based media object
          Cras sit amet nibh libero, in gravida nulla (...)
      %li.media.my-4
        .media-body
          %a.text-black{ href: '' }
            %h5.mt-0.mb-1.font-weight-bold
              List-based media object
          Cras sit amet nibh libero, in gravida nulla (...)
      %li.media
        .media-body
          %a.text-black{ href: '' }
            %h5.mt-0.mb-1.font-weight-bold
              List-based media object
          Cras sit amet nibh libero, in gravida nulla (...)

app/views/news/_selector.html.haml
= form_tag('news#index', method: "get", id: "category_search", class: 'filter') do
  .col-sm-12
    .search
      .input-group.mb-3
        = text_field_tag  :title_search,
          params[:search],
          placeholder:  t('news.search.field'),
          class: "form-control"
        .input-group-append
          %button.btn.btn-outline-secondary{ type: 'submit' }
            = t ('news.selector.button')
  %br
  - @categories.each do |category|
    .item
      .form-check.col-xl-3
        = check_box_tag 'by_categories[]',
          category.id,
          params.key?(:by_categories) ? params[:by_categories].include?(category.id.to_s) : false,
          id: category.name, class: 'box'
        = label_tag category.name

app/views/news/_share_buttons.html.haml
= link_to fa_icon('facebook-square'),
"https://www.facebook.com/sharer/sharer.php?u=#{news_url(news)}&quote=#{news.title}",
class: 'social-icon popup ml-2',
'data-width': 600,
'data-height': 400

= link_to fa_icon('twitter-square'),
"http://twitter.com/share?text=#{news.title}&url=#{news_url(news)}",
class: 'social-icon popup ml-1',
'data-width': 600,
'data-height': 400

app/views/news/edit.html.haml
.container
  %section.mt-4
    .row.justify-content-center
      .col-md-8.mb-4
        %h3.text-center.mb-4
          = t('news.edit.edit_news')
        = render 'form'

app/views/news/index.html.haml
.container.p-0
  .row.justify-content-center.mt-4.p-0
    .col-lg-7
      %h3
        = render 'selector'
      %h2
        = t('news.index.university_news')
      %p
        = t('news.index.sort_by')
        = link_to t('news.links.popular'), news_index_path(ordered_by_views: true), remote: true,
          id: 'most-popular', class: 'ml-2'
        = link_to t('news.links.recent'), news_index_path(ordered_by_views: false), remote: true,
          id: 'most-popular', class: 'ml-2'
      #news
        = render @news
    = render 'aside_bar'
  = will_paginate @news

app/views/news/index.js.haml
$('#news').html("#{ j (render 'news') }");

app/views/news/new.html.haml
.container
  %section.mt-4
    .row.justify-content-center
      .col-md-8.mb-4
        %h3.text-center.mb-4
          = t('news.new.add_news')
        = render 'form'

app/views/news/show.html.haml
.container
  %section.mt-4
    .row.justify-content-center
      .col-md-8
        .card-body
          %h1.display-2.m-0.mb-4.mr-2
            = @news.title
          %h3.mb-3
            = @news.short_information
          .m-4.user-short-info
            .thumbnail-social-icon.mr-2
              = link_to image_tag(@news.user.avatar_url), user_path(@news.user.id)
            %p.ml-2.mb-1
              %b
                = link_to_user(@news.user)
            %p.m-0
              = @news.created_at.to_date
          .view.overlay.rounded-top
          .thumbnail-news
            = image_tag @news.image_url
          %h4.text-left.mt-4.mb-2
            = @news.body.html_safe
          %p.mt-4.text-right
            = t('news.links.share')
            = render 'share_buttons', news: @news
          %br
        %ul
          = render 'comments/form'
          = render partial: 'comments/comment', collection: @news.comments
      = render 'related_news'

app/views/news/user_news.html.haml
.container.p-0
  %h1.mb-3
    = t ('users.edit.profile')
  .row
    .col-md-5.col-xl-3
      = render 'users/menu', user: @user
    .col-md-7.col-xl-9
      .card
        .card-header
          %h5.card-title.mb-0
            = t ('users.edit.news')
        .card-body
          = render @news.ordered_by_views
          = will_paginate @news